Add `chmod -R 777` to `/opt/conda`
rapidsai/mambaforge-cuda pull request #26
Opened 2023-03-27 18:09 UTC by raydouglass

In order for downstream images to install conda packages as a non-root user, we need to expand the permissions of the `/opt/conda` directory in this image.

Required for https://github.com/rapidsai/docker/issues/539

I tested locally like so:

`docker buildx build -f Dockerfile -t rapidsai/mambaforge-cuda-777:cuda11.8-base-ubuntu22.04-py3.10 --build-arg CUDA_VER=11.8.0 --build-arg LINUX_VER=ubuntu22.04 --build-arg PYTHON_VER=3.10 .`

Then build this Dockerfile:
```Dockerfile
FROM rapidsai/mambaforge-cuda-777:cuda11.8-base-ubuntu22.04-py3.10

RUN useradd -rm -d /home/rapids -s /bin/bash -g root -G sudo -u 1001 rapids

USER rapids

RUN mamba install -n base -y curl
```

2023-03-27 18:23 UTC, bdice requested changes
I'd like to see a solution that doesn't modify _everything_ to be executable (`+x`). It also doesn't feel like we're using privileges correctly. We should be able to resolve this by changing users before installing mamba, or some other way?

2023-03-27 19:11 UTC, bdice approved these changes
This is much closer to what I was hoping for! Let's rename the PR title to match the implementation, and I have one question about whether we should re-order some commands. Otherwise this could be merged in its current state.

2023-03-27 19:11 UTC, bdice commented on Dockerfile
> +USER root
Should we execute the apt-get and other "root" commands first, before copying in conda as the non-root user? Does the image need to end up in "root" mode?

2023-03-29 14:15 UTC, ajschmidt8 reviewed
in an attempt to keep the changes to the base images to a minimum, I think we should experiment with the suggestions linked below.

- https://docs.anaconda.com/anaconda/install/multi-user/#multi-user-anaconda-installation-on-linux

they suggest utilizing linux groups to provide write access to a global conda installation.

so we could set up the group in this base image, but create the user in the downstream end-user images.

If this works, I think this should be the approach we adopt

2023-03-30 18:28 UTC, raydouglass commented
> they suggest utilizing linux groups to provide write access to a global conda installation.

The latest commit now uses a `conda` group and some `chmod`/`umask` commands to control the write/setgid permissions. This appears to work for downstream images.

2023-04-05 17:16 UTC, ajschmidt8 approved these changes
<details><summary>Changeset</summary>
<p>

```diff
diff --git a/Dockerfile b/Dockerfile
index fccc8ff..7b31691 100644
--- a/Dockerfile
+++ b/Dockerfile
@@ -1,6 +1,6 @@
 ARG CUDA_VER=11.4.0
 ARG LINUX_VER=ubuntu20.04
-FROM nvidia/cuda:${CUDA_VER}-base-${LINUX_VER}
+FROM nvidia/cuda:${CUDA_VER}-base-${LINUX_VER} as base
 
 ARG LINUX_VER
 ARG PYTHON_VER=3.9
@@ -61,3 +61,11 @@ RUN case "${LINUX_VER}" in \
       echo "Unsupported LINUX_VER: ${LINUX_VER}" && exit 1; \
       ;; \
   esac
+
+FROM base as enduser
+
+RUN useradd -m -g conda rapids;
+
+USER rapids
+
+RUN mamba install -y django; conda remove -y --force-remove cffi
```
</p>
</details> 

I tested this PR locally by running `docker build .` with the changeset above and confirmed that the non-`root` user had access to add and remove packages from the `base` environment.

2023-04-05 17:30 UTC, merged